version: '3.8'
services:
  service1:
    container_name: service1
    image: orlandlleshi/project2-service-1
    build: ./service1
    ports: 
      - target: 5000
        published: 5000
    environment:
       DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 3
      
  character_api:
    container_name: character_api
    image: orlandlleshi/project2-service-2
    build: ./character_api
    ports: 
      - target: 5001
    deploy:
      replicas: 3

  background_api: 
    container_name: background_api
    image: orlandlleshi/project2-service-3
    build: ./background_api
    ports: 
      - target: 5002
    deploy:
      replicas: 3  

  endpoint_api:
    container_name: endpoint_api
    image: orlandlleshi/project2-service-4
    build: ./endpoint_api
    ports: 
      - target: 5003
    deploy:
      replicas: 3