---
# tasks file for docker

- name: Install requirements
  apt:
    state: latest
    update_cache: true
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    -python3-pip
    python3

- name: Add Docker APT Repository 
  ansible.builtin.apt_repository:
  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename|lower }} stable
  state: present

- name: Add GPG key
  ansible.builtin.apt_key:
  url: https://download.docker.com/linux/ubuntu/gpg
  state: present

- name: Install Docker with APT
  apt: 
    state: latest 
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Add Ubuntu user to docker group 
  user: 
    name: orlandlleshi  
    groups: docker
    append: yes
- name: pip docker
  pip: 
    executable: pip3
    name: docker

- name: Add a jenkins user
  ansible.builtin.user:
  name: jenkins
  groups: docker
  append: yes