---
# tasks file for worker
- name: Add worker 
  docker_swarm:
    advertise_addr: "{{ inventory_hostname  }}"
    state: join
    remote_addrs: [ 'flask:2337']
    join_token: " {{ hostvars['flask']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"