---
# tasks file for manager
- name: Initialise a new swarm
  docker_swarm:
    state: present
  register: swarm info 

- name: Deploy stack
  docker_stack:
    state: present
    name: project
    compose:
      - ~/docker_compose.yaml  