---
# tasks file for manager
- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
  register: swarm_info 

#- name: Deploy stack
#  docker_stack:
#    state: present
#    name: project
#    compose:
#      - ~/docker-compose.yaml 
#    pkg:
#    - jsondiff
#    - pyyaml 